extensions:
  health_check:
  pprof:
    endpoint: 0.0.0.0:1777
  awsproxy:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:

exporters:
  logging:
    loglevel: debug
  awsxray:
    region: "us-east-1"
  awsemf:
    region: "us-east-1"
    # log_group_name: "MSBaselines"
    # log_stream_name: "MSBaselines"
    namespace: "MSBaselines"
    dimension_rollup_option: 1
    # Convert attributes to metric labels
    resource_to_telemetry_conversion:
      enabled: true

service:
  pipelines:
    traces:
      receivers:
        - otlp

      exporters:
        - awsxray
    metrics:
      receivers:
        - otlp
      exporters:
        - awsemf

  extensions:
    - pprof
    - awsproxy
  telemetry:
    logs:
      level: debug
